#if !canImport(ObjectiveC)
import XCTest

extension ProtectedTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__ProtectedTests = [
    ("testThatProtectedAPIIsSafe", testThatProtectedAPIIsSafe),
    ("testThatProtectedValuesAreAccessedSafely", testThatProtectedValuesAreAccessedSafely),
  ]
}

extension ProtectedWrapperTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__ProtectedWrapperTests = [
    ("testThatDynamicMembersAreAccessedSafely", testThatDynamicMembersAreAccessedSafely),
    ("testThatDynamicMembersAreSetSafely", testThatDynamicMembersAreSetSafely),
    ("testThatProjectedAPIIsAccessedSafely", testThatProjectedAPIIsAccessedSafely),
    ("testThatWrappedValuesAreAccessedSafely", testThatWrappedValuesAreAccessedSafely),
  ]
}

public func __allTests() -> [XCTestCaseEntry] {
  return [
    testCase(ProtectedTests.__allTests__ProtectedTests),
    testCase(ProtectedWrapperTests.__allTests__ProtectedWrapperTests),
  ]
}
#endif
